root: true

env:
  # https://eslint.org/docs/user-guide/configuring#specifying-environments
  # add all Node.js global variables and Node.js scoping.
  node: true

extends:
  # https://www.npmjs.com/package/eslint-config-airbnb-base
  - eslint-config-airbnb-base

rules:
  # allow for development purposes
  # https://eslint.org/docs/rules/no-console
  no-console: 0
